### ISSUE TITLE
Describe database

### ISSUE THREAD

**Issue by Minimata** [HE-Arc/WafflePancake-Studios#3]
Describe and document database together with schematics (entity-relationship model).

**Comment by greut** [comment]
aka [_Models_](https://docs.djangoproject.com/en/1.10/topics/db/models/)

**Comment by Minimata** [comment]
Yeah but "Describe models" is a bit short and let's not jump into the code too quickly now, shall we.
"Take a sheet of paper and write your shit down with a pencil before coding anything you fucktards" -Every professor at HE-Arc

**Comment by greut** [comment]
like in entity-relationship model, :+1:

**Comment by Minimata** [comment]
Precisely ! I was looking for the term, thx
